"""INITIAL2

Revision ID: 019400437761
Revises: 2e79507b5563
Create Date: 2025-03-15 23:18:59.297043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '019400437761'
down_revision: Union[str, None] = '2e79507b5563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza_ingredients',
    sa.Column('pizza_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], ),
    sa.PrimaryKeyConstraint('pizza_id', 'ingredient_id')
    )
    op.drop_table('product_ingredients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_ingredients',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name='product_ingredients_ingredient_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_ingredients_product_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', 'ingredient_id', name='product_ingredients_pkey')
    )
    op.drop_table('pizza_ingredients')
    # ### end Alembic commands ###
