"""INITIAL3

Revision ID: 1262d51bd547
Revises: 019400437761
Create Date: 2025-04-05 14:40:14.972575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1262d51bd547'
down_revision: Union[str, None] = '019400437761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_store_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'store_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_store_id_fkey', 'categories', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###
